### ISSUE TITLE
[Roadmap] AIOS Roadmap Q2 2024

### ISSUE THREAD

**Issue by TataKKKL** [agiresearch/AIOS#107]
This document outlines the features in the AIOS roadmap for Q2 2024. Please feel free to discuss and contribute to the specific features through related Issues or PRs, and add any other topics you'd like to talk about in this issue.

## Device Support & LLM inference acceleration integration
- [x] ollama support: https://github.com/agiresearch/AIOS/pull/108 
- [x] vllm support on GPU

## Agent configuration
- [x] move agent creation logic from AIOS to OpenAGI
- [x] enable tool callings
    - [x] chatgpt-based tool calling
        https://github.com/agiresearch/OpenAGI/pull/50
        https://github.com/agiresearch/AIOS/pull/116
    - [x] open-sourced llm tool calling 
- [x] add an agent (travel agent) with more tool callings
- [ ] add an agent with self planning and code interpretation for action execution

## More & better documentation
- [x] add evaluation script and add agent-level and request-level evaluation metrics
  - [x] https://github.com/agiresearch/AIOS/pull/93
  - [x] https://github.com/agiresearch/AIOS/pull/96
  - [x] https://github.com/agiresearch/AIOS/pull/100
- [x] improve documentation and environment set up
  - [x] https://github.com/agiresearch/AIOS/pull/97
  - [x] https://github.com/agiresearch/AIOS/pull/98
  - [x] https://github.com/agiresearch/AIOS/pull/99
- [x] add more benchmarks
- [x] update the architecture diagram of AIOS

## Better demo
- [x] ChatUI

## Streaming output
- [ ] Streaming output for API-based llm to support context switch

## Testing
- [ ] modify unit test
  - [x] https://github.com/agiresearch/OpenAGI/pull/48
  - [x] https://github.com/agiresearch/AIOS/pull/113
- [ ] add integration test
- [ ] Github workflow https://github.com/agiresearch/AIOS/issues/134

## Package & Documentation
- [x] package and release OpenAGI as the PyPI library
- [ ] package and release AIOS as executive files
    - [ ] On Linux(Debian), apt install
    - [ ] On Windows, download as .exe
    - [ ] On MacOS, brew install
- [x] add documentation for OpenAGI and AIOS

**Comment by itsthemoon** [comment]
hi, I am interested in working on: add an agent with more tool callings

**Comment by dongyuanjushi** [comment]
A travel agent can be considered by calling multiple search tools (hotels, flights, restaurants). Or it is possible to come up with other agent, which will call multiple tools during execution. A sub-channel can be created for follow up @itsthemoon .

**Comment by itsthemoon** [comment]
> A travel agent can be considered by calling multiple search tools (hotels, flights, restaurants). Or it is possible to come up with other agent, which will call multiple tools during execution. A sub-channel can be created for follow up @itsthemoon .

I created an issue [here](https://github.com/agiresearch/OpenAGI/issues/46) and I am currently working on the implementation.

**Comment by ArnoldIOI** [comment]
I'll be working on the langgraph -based RAG agent. I've opened a new issue [here](https://github.com/agiresearch/OpenAGI/issues/59).
