### ISSUE TITLE
[TODO for AIOS v0.1.0 Release] 

### ISSUE THREAD

**Issue by dongyuanjushi** [agiresearch/AIOS#262]
### TODO for AIOS v0.1.0 Release

- [x] One-click install (pip or brew or apt install)
- [x] Verify all agents work
      https://github.com/agiresearch/AIOS/pull/263
- [x] Separate agent packaging and agent upload
- [ ] Agent upload and download for the UI
- [ ] Sidebar of the agentchat and agenthub
- [x] Press enter after@ to select an agent
- [ ] IP-based usage limitation (simple method)
- [x] Documentation
    - [ ] Installation guide
    - [ ] Usage guide
    - [ ] How to do agent upload and download

Optional for v0.1.0:
- [ ] AIOS terminal
- [ ] Agent approval mechanism

**Comment by joshprk** [comment]
https://github.com/agiresearch/AIOS/pull/297
